[env]
openssl_path = "openssl"

[inbound-http]
enable = true
listen = "0.0.0.0:7890"

[outbound]

[log]

[dns]
cache-expiration = 7200
load-local-host-file = true

[dns-server]
normal = "udp://223.5.5.5"
secure = "tls://101.101.101.101"
