[env]
openssl_path = "D:\\msys64\\usr\\bin\\openssl.exe"


[inbound.normal]
enable = true
listen = "http://0.0.0.0:7890"

[inbound.secure]
enable = true
listen = "https://0.0.0.0:7899"
hostname = "localhost"


[outbound.fanq]
enable = true
origin = "http://127.0.0.1:10809"

[outbound.tor]
enable = true
origin = "http://127.0.0.1:8118"


[log]
level = 5


[dns]
cache-expiration = 7200
load-local-host-file = true


[dns-server]
normal = "udp://114.114.114.114"
secure = "tls://101.101.101.101"
